# Generated by Django 2.2.1 on 2019-06-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_paginationsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paginationsettings',
            old_name='ITEMS_PER_PAGE',
            new_name='items_per_page',
        ),
    ]
