# Generated by Django 2.2.1 on 2019-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_auto_20190604_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginationsettings',
            name='items_per_page',
            field=models.IntegerField(default=10),
        ),
    ]
