# Generated by Django 2.2.1 on 2019-06-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0006_auto_20190611_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDocument',
        ),
    ]
