# Generated by Django 2.2.1 on 2019-06-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0008_customdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdocument',
            name='source',
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Event'),
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Group'),
        ),
        migrations.AlterField(
            model_name='customdocument',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Region'),
        ),
    ]
