# Generated by Django 2.2.1 on 2019-06-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_auto_20190611_1452'),
        ('util', '0009_auto_20190611_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdocument',
            name='lap_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lap date'),
        ),
        migrations.AddField(
            model_name='customdocument',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Track'),
        ),
    ]
