# Generated by Django 2.2.1 on 2019-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0010_auto_20190611_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginationsettings',
            name='page_range',
            field=models.IntegerField(default=5),
        ),
    ]
