# Generated by Django 2.2.1 on 2019-05-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190526_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=255),
        ),
    ]
