# Generated by Django 2.2.1 on 2019-05-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20190528_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racer',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, to='records.Sponsor'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
