# Generated by Django 2.2.1 on 2019-05-29 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0006_auto_20190528_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
