# Generated by Django 2.2.1 on 2019-05-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20190529_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
