# Generated by Django 2.2.1 on 2019-05-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20190530_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.Event'),
        ),
    ]
