# Generated by Django 2.2.1 on 2019-05-31 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_lappage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.Car'),
            preserve_default=False,
        ),
    ]
