# Generated by Django 2.2.1 on 2019-05-31 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_lap_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='car',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='records.Car'),
        ),
    ]
