# Generated by Django 2.2.1 on 2019-05-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_auto_20190531_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='car',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='records.Car'),
            preserve_default=False,
        ),
    ]
