# Generated by Django 2.2.1 on 2019-06-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('records', '0018_auto_20190531_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LapPage',
        ),
    ]
