# Generated by Django 2.2.1 on 2019-06-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_auto_20190610_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.Group'),
            preserve_default=False,
        ),
    ]
