# Generated by Django 2.2.1 on 2019-06-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_lap_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lap',
            constraint=models.UniqueConstraint(fields=('racer', 'group', 'raceclass', 'track', 'lap_date'), name='key'),
        ),
    ]
