# Generated by Django 2.2.1 on 2019-06-10 21:02

from django.db import migrations, models
import records.models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_lap_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
