# Generated by Django 2.2.1 on 2019-06-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_auto_20190610_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='key',
        ),
    ]
