# Generated by Django 2.2.1 on 2019-06-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_remove_lap_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lap',
            name='key',
        ),
    ]
