# Generated by Django 2.2.1 on 2020-01-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('aloha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlohaPage',
        ),
    ]
